**Simple Program in python**

In [3]:
print("hello world")

hello world


**Subject:-** Statical Machine Learning - MSc.CS(IIsem) **[Practical]**

In [4]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [6]:
# back to cpu
# all pre installed packages
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print(torch.__version__)
# cu stands for cuda version

2.5.1+cu124


**Introduction to Tensors**

**Creating Tensors**

PyTorch tensors are created using torch.Tensor()

see Tensors in pytorch documentation

In [7]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim  # size

0

In [9]:
# get tensor back as python int
scalar.item()

7

In [ ]:
vector = torch.tensor([7,8]) # size 1x1
vector

tensor([7, 8])

In [11]:
# gives dimension scalar has 0,
# vector has one(1 dimension, simple remember as have 1 box )
vector.ndim

NameError: name 'vector' is not defined

In [12]:
# shape gives us no of elements
# ndim is simple no of pair of box brackets
vector.shape

NameError: name 'vector' is not defined

In [13]:
# MATRIX 2x2
MATRIX = torch.tensor([[1,2],
                      [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In PyTorch Any time you convert data into numbers its of a tensor data type.

In [ ]:
MATRIX.ndim

2

In [14]:
MATRIX[0]

tensor([1, 2])

In [ ]:
torch.Size([2, 2])

torch.Size([2, 2])

In [15]:
# TENSOR 3x3
TENSOR = torch.tensor([[[5,6,7],
                        [2,4,5],
                        [0,9,8]]])
TENSOR

tensor([[[5, 6, 7],
         [2, 4, 5],
         [0, 9, 8]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[5, 6, 7],
        [2, 4, 5],
        [0, 9, 8]])

In [19]:
TENSOR[0][1], TENSOR[0][2], TENSOR[0][0]

(tensor([2, 4, 5]), tensor([0, 9, 8]), tensor([5, 6, 7]))

In [ ]:
TENSOR[0][0][0], TENSOR[0][2][1]

In [20]:
TENSOR[0][0][0], TENSOR[0][2][1]

(tensor(5), tensor(9))

Random Tensors
are imp bcoz the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers ...

In [21]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1618, 0.1820, 0.4888, 0.2081],
        [0.4104, 0.2090, 0.5850, 0.3512],
        [0.8904, 0.0306, 0.4044, 0.6535]])

In [22]:
# here we have 2 box brackets, so 2 dimensions
random_tensor.ndim

2

In [23]:
rand1 = torch.rand(1, 3, 4)
rand1

tensor([[[0.9965, 0.2848, 0.8048, 0.1656],
         [0.7917, 0.9883, 0.6052, 0.6050],
         [0.4397, 0.0183, 0.5769, 0.0213]]])

In [24]:
# now 3 dim
rand1.ndim

3

In [25]:
# create a random tensor with similar shape to an iamge tensor
# image_size = torch.rand(size=(height, width, color_channel))

random_image_size_tensor = torch.rand(size=(224, 224, 3))
# height, width, color channels(R, G, B)

random_image_size_tensor.shape,
random_image_size_tensor.ndim

3

In [26]:
random_image_size_tensor.shape
# sometimes it shows [3, 224, 224] color channel comes first

torch.Size([224, 224, 3])

In [27]:
random_image_size_tensor
# creating all the tensors of shape [224,224,3] in background

tensor([[[0.7178, 0.2211, 0.8343],
         [0.8600, 0.4084, 0.1492],
         [0.9175, 0.5618, 0.2814],
         ...,
         [0.3387, 0.6984, 0.7270],
         [0.2306, 0.2717, 0.6668],
         [0.4072, 0.3352, 0.1791]],

        [[0.3767, 0.8257, 0.8191],
         [0.5271, 0.2083, 0.1093],
         [0.1979, 0.4594, 0.2535],
         ...,
         [0.1343, 0.8004, 0.7571],
         [0.1586, 0.8836, 0.3281],
         [0.3370, 0.6548, 0.1075]],

        [[0.7530, 0.8350, 0.7006],
         [0.1210, 0.8353, 0.1678],
         [0.2684, 0.7605, 0.6747],
         ...,
         [0.4867, 0.8153, 0.0343],
         [0.4320, 0.0847, 0.3071],
         [0.3904, 0.5513, 0.2847]],

        ...,

        [[0.5119, 0.1258, 0.9282],
         [0.1997, 0.8552, 0.4999],
         [0.9883, 0.1662, 0.2201],
         ...,
         [0.4076, 0.7034, 0.4817],
         [0.7360, 0.4672, 0.0241],
         [0.4799, 0.0268, 0.0966]],

        [[0.8413, 0.6960, 0.3579],
         [0.6294, 0.1510, 0.9398],
         [0.

In [28]:
#creating my random tensor
another_random_tensor = torch.rand(5, 10, 10)

another_random_tensor.shape, another_random_tensor.ndim

(torch.Size([5, 10, 10]), 3)

In [29]:
another_random_tensor

tensor([[[0.9898, 0.1785, 0.2251, 0.6029, 0.9037, 0.6606, 0.8527, 0.2130,
          0.8125, 0.3425],
         [0.3496, 0.4484, 0.5972, 0.3833, 0.1366, 0.4021, 0.9564, 0.5149,
          0.8864, 0.2447],
         [0.6736, 0.7231, 0.9223, 0.4427, 0.8718, 0.7039, 0.2181, 0.7852,
          0.1921, 0.7125],
         [0.9097, 0.4087, 0.8784, 0.3745, 0.2422, 0.3009, 0.8098, 0.6819,
          0.4671, 0.8821],
         [0.7147, 0.7463, 0.6273, 0.1190, 0.3928, 0.5183, 0.2322, 0.3563,
          0.0691, 0.8215],
         [0.3722, 0.1668, 0.2392, 0.2240, 0.2865, 0.8735, 0.9243, 0.9363,
          0.8231, 0.3939],
         [0.0619, 0.0118, 0.5799, 0.4580, 0.3525, 0.7849, 0.8422, 0.0335,
          0.9275, 0.7595],
         [0.1858, 0.6248, 0.7739, 0.1117, 0.3223, 0.3078, 0.9416, 0.0037,
          0.4842, 0.1227],
         [0.9811, 0.0652, 0.6009, 0.1881, 0.7660, 0.1984, 0.4899, 0.0079,
          0.0397, 0.5543],
         [0.4112, 0.3308, 0.9611, 0.7533, 0.5138, 0.9231, 0.4924, 0.5215,
          0.7556,

In [30]:
# we can use size also inside rand fuction
torch.rand(size=(3,3))

tensor([[0.4642, 0.5904, 0.6955],
        [0.3646, 0.2716, 0.6744],
        [0.2965, 0.5134, 0.3860]])

**Zeroes and Ones**

Used in mask values to in range of 0,1

In [31]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
# create a tensor of all 1's
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
# dtype gives data type
ones.dtype

torch.float32

In [35]:
# by default torch gives us float values
random_tensor.dtype

torch.float32

**creating a range of tensors and tensors-like**  




In [36]:
# use torch.range() will deprecate in future so don't use
torch.range(0, 10)

<ipython-input-36-d6e4fa2f3546>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# use arange instead of range
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# from 1 to 10
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# check documentation of arange
test = torch.arange(start=0, end=1000, step=50)
test

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Tensor datatypes**

**Note** Tensor datatypes is one of the **3 big** erros you'll run into with torch and in DL.

1. Tensors not right datatype
2. Tensors not right shape.

3. Tensors not on the right device. (cpu, cuda, gpu etc.)

In [ ]:
# float 32 tensor
f32tensor = torch.tensor([3.0,6.0,9.0],
                         dtype=None, # what datatype is the tensor float32 or float16
                         device=None, # what device is your tensor on,  cpu, gpu, cuda or etc.
                         requires_grad=False) # wheather or not to track gradients with this tensors operations

f32tensor

tensor([3., 6., 9.])

In [ ]:
f32tensor.dtype

torch.float32

In [ ]:
# you can change data type also
#f32tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float16)
f32tensor.dtype

torch.float32

In [ ]:
# change data type f31 to f16
f16tensor = f32tensor.type(torch.float16) # half for float16
f16tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# Run multiple examples and play with different datatypes of tensors

f16tensor * f32tensor

tensor([ 9., 36., 81.])

In [ ]:
int32tensor =  torch.tensor([2, 7, 9], dtype=torch.int32)
int32tensor

tensor([2, 7, 9], dtype=torch.int32)

In [ ]:
f32tensor * int32tensor

tensor([ 6., 42., 81.])

**disallowed (RuntimeError: result type can't be cast to the desired output type):**

>>> int_tensor *= float_tensor
>>> bool_tensor *= int_tensor
>>> bool_tensor *= uint_tensor
>>> float_tensor *=complex_float_tensor

Remember it!

In [ ]:
# THIS IS INTENTIONALLY CREATED ERROR

# char * int not allowed (Will create error)
# charTensor = torch.tensor(['a', 'b', 'c'] dtype=torch.char)

# int32tensor * charTensor

**Getting information from tensors (Tensor Attributes)**

1. Tensors not right datatype - to do get datatype from a tensor, you can use tensor.dtype
2. Tensors not right shape. - to get shape from a tensor, you can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, you can use tensor.device


In [ ]:
# create some tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6700, 0.9111, 0.1117, 0.4300],
        [0.2759, 0.4559, 0.4625, 0.7505],
        [0.0070, 0.4668, 0.4801, 0.9650]])

In [ ]:
# let's find information about this random tensor
random_tensor.dtype, random_tensor.shape, random_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

In [ ]:
# tensor_name.size() and tensor.shape gives same output

print(random_tensor);
print(f"The shape is: {random_tensor.shape}")
print(f"Size is same but its function : {random_tensor.size()}")

tensor([[0.6700, 0.9111, 0.1117, 0.4300],
        [0.2759, 0.4559, 0.4625, 0.7505],
        [0.0070, 0.4668, 0.4801, 0.9650]])
The shape is: torch.Size([3, 4])
Size is same but its function : torch.Size([3, 4])


**Manipulating Tensors (tensor operations)**

includes

1. Addition
2. Substraction
3. Multiplication (element-wise)
4. Division
5. Matrix multiplication

In [40]:
# scalar addition (add 10)
tensor = torch.tensor([4, 6, 7])
tensor + 11

tensor([15, 17, 18])

In [ ]:
# scalar multiplication (Element wise)
tensor * 11

tensor([44, 66, 77])

In [41]:
# tensor substraction
tensor - 11

tensor([-7, -5, -4])

**Matrix Multiplication**

Two main ways to multiply in neural networks & deep learnings

1. Element wise (Scalar Mul)
2. Matrix multiplication (dot product)

In [37]:
mat1 = torch.tensor([[1,2,3],
                     [3,5,7]], dtype=torch.int32)
mat2 = torch.tensor([[7,5],
                     [8,10],
                     [11,12]], dtype=torch.int32)

mat1.shape, mat2.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [42]:
# Element wise (scalar) multiplication

# tensor * tensor

print(tensor,  '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([4, 6, 7]) * tensor([4, 6, 7])
Equals: tensor([16, 36, 49])


In [43]:
# matrix multiplication

torch.matmul(tensor, tensor)

tensor(101)

**One of the most common errors in DL and NN are shape errors**

See Visualizations of matrix multiplication in matrixmultiplication.xyz

Their are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimentions** must match:

@ is equal to matmul function

  (3, 2) @ (3, 2) won't work

  (2, 3) @ (3, 2) will work
  
  (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the **outer dimensions**:

*  (2, 3) @ (3, 2) -> (2, 2)
*  (3, 2) @ (2, 3) -> (3, 3)

In [44]:
# matrix multiplication of 2 matrices
# here %%time gives cpu time
%%time
torch.matmul(mat1, mat2)

CPU times: user 1.1 ms, sys: 17 µs, total: 1.11 ms
Wall time: 1.18 ms


tensor([[ 56,  61],
        [138, 149]], dtype=torch.int32)

In [46]:
mat1 @ mat2  # @ is short form for matmul

tensor([[ 56,  61],
        [138, 149]], dtype=torch.int32)

**The most common error in PyTorch or Tensorflow**

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

inner dim must be equal

(3, 2) @ (3, 2) won't work

In [47]:
# will generate error
# torch.rand(3, 2) @ torch.rand(3, 2)

In [48]:
# When inner dimensions match
torch.rand(3, 2) @ torch.rand(2, 3)

tensor([[0.8278, 0.5069, 0.8325],
        [0.6701, 0.3843, 0.6803],
        [0.4253, 0.2655, 0.4265]])

**Most common errors in DL: (shape errors)**

In [49]:
# shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,7]])

tensor_B = torch.tensor([[7, 11],
                         [6, 12],
                         [9, 13]])

# torch.mm is the alias for less code for matmul
# torch.mm(tensor_A, tensor_B)  # SHAPE ERROR

# to fix our problem we have to manipulate the shape of one of our tensors using
# a transpose operation. (switching the axes or dimentions of a given tensor)

tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  6,  9],
         [11, 12, 13]]),
 torch.Size([2, 3]))

In [50]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [51]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 29,  30,  35],
        [ 65,  66,  79],
        [112, 114, 136]])

In [52]:
# The matrix multiplication operation works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} inner dimensions matched")
print("Output:\n")

output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")
#

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) inner dimensions matched
Output:

tensor([[ 29,  30,  35],
        [ 65,  66,  79],
        [112, 114, 136]])

Output shape: torch.Size([3, 3])


**Finding the min, max, mean and sum etc. (Tensor aggregations)**

In [53]:
# lets create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [54]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [55]:
# find the man of tensor
torch.max(x), x.max()

(tensor(91), tensor(91))

In [56]:
# find the mean (float, or complex data type)
# torch.mean(x) # datatype mismatch its long

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [57]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

**Finding the positional min and max**

In [58]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [59]:
# find the position in tensor that has the minimum value with argmin()
x.argmin() # it returns index position of target tensor where the min value occurs

tensor(0)

In [60]:
x[0]

tensor(1)

In [61]:
# find the position in tensor that has a max value
x.argmax()  # will use it in softmax activation fun


tensor(9)

In [62]:
x[9]

tensor(91)

**Reshaping, stacking, squeezing and unsqueezing tensors (Helps in fixing dim(dimension) issues)**

*  Reshaping - reshapes an input tensor to a defined shape.
*  View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
*  Stacking-Combine multiple tensors on top of each other(vstack) or side by side(hstack)
*  squeeze- removes all 1 dimensions from a tensor
*  Unsqueeze - add a 1 dimension to a target tensor
*  Permute-Return a view of the input with dimensions permuted(swapped) in a certain way


In [63]:
# let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [64]:
# reshape: add an extra dimension (has to be compatible with the original size)
#x_reshaped = x.reshape(1,9) # convert it in 2D
#x_reshaped = x.reshape(9,1) # convert it in [9,1]
x_reshaped = x.reshape(3,3) # convert it in [3, 3]
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [65]:
# change the view
# here z is just the view, it shares memory with original variable.
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [66]:
# change in z changes x(bcause a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z , x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [67]:
# stack tensors on top of each other (similar to vstack)
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [68]:
# stack tensors on top of each other similar to hstack
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [69]:
# vstack
torch.vstack((x,x))

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [70]:
# torch hstack (Stack tensors in sequence horizontally )
torch.hstack((x,x,x,x))

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [71]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [72]:
x_reshaped.shape

torch.Size([3, 3])

In [73]:
x_reshaped.squeeze()

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [74]:
# it only removes 1D arrays so got shape 9 only
x.squeeze().shape, x_reshaped.squeeze().shape

print(f"Previous tensor: {x}")
print(f"Previous shape: {x.shape}")

y = x.resize(1,9)
print("Lets resize it first")
print(f"Resized shape {y} converted to 2D")

# remove extra dimension from y
y_squeezed = y.squeeze()
print(f"\nNew tensor: {y_squeezed}")
print(f"New shape: {y_squeezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
Lets resize it first
Resized shape tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) converted to 2D

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


/usr/local/lib/python3.11/dist-packages/torch/_tensor.py:955: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension(dim)
print(f"Previous target: {y_squeezed}")
print(f"Previous shape: {y_squeezed.shape}")

# add an extra dimension with unsqueeze
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {y_unsqueezed}")
print(f"New shape: {y_unsqueezed.shape}")
#

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [75]:
y_unsqueezed = y_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {y_unsqueezed}")
print(f"New shape: {y_unsqueezed.shape}")


New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [77]:
# torch.permute- rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [ht, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order

x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [78]:
# x_original
x_original[0, 0, 0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

time : 3 Hrs :23 Min


**Indexing (selecting data from tensors.)**

Indexing with PyTorch(Tensor is main data type) is similar to indexing with NumPy (array as main data type).



In [79]:
# create a Tensor

import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [80]:
# Let's index on our new Tensor (dim=0)
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [81]:
# now index on our middle box bracket (dim=1)
print(x[0][0], x[0][1], x[0][2])
# OR
print(x[0, 0])  # Gives same output

tensor([1, 2, 3]) tensor([4, 5, 6]) tensor([7, 8, 9])
tensor([1, 2, 3])


In [82]:
# lets index on the most inner box bracket (dim=2) last dimension
x[0][0][1], x[0][2][1], x[0][1][1],x[0][2][2]


(tensor(2), tensor(8), tensor(5), tensor(9))

In [83]:
# you can also use ":" to select 'all' of the target dimension.
x[:, 0]

tensor([[1, 2, 3]])

In [84]:
#  Get all values of 0th and 1st dimensions, but only index 1 of 2nd dimension.
x[:, :, 1]

tensor([[2, 5, 8]])

In [85]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 2], x[:, 1, 1], x[:, 1, 0] , x[0, 1, 1]

# here we case use 0 instead of ":" sign, gives same result.

(tensor([6]), tensor([5]), tensor([4]), tensor(5))

In [86]:
# Get index 0 of 0th dimension and all values of 2nd dimension

x[0,0,:], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [87]:
# index on x to return 9
x[0, 2, 2]

tensor(9)

In [88]:
# index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

In [89]:
x[:, :, 0], x[:, :, 1], x[:, :, 2]
# Displaying all columns in matrix

(tensor([[1, 4, 7]]), tensor([[2, 5, 8]]), tensor([[3, 6, 9]]))

In [90]:
x[:, 0, :], x[:, 1, :], x[:, 2, :]
# Displaying all rows 1 by 1 in matrix.

(tensor([[1, 2, 3]]), tensor([[4, 5, 6]]), tensor([[7, 8, 9]]))

**PyTorch tensors and NumPy**

NumPy is a popular scientific pytohn numerical computing liabrary.
and because of this, PyTorch has functionality to interact with it.

* Data in NumPy array, want in PyTorch tensor-> torch.from_numpy(ndarray)
* PyTorch tensor->NumPy -> torch.Tensor.numpy()


In [91]:
# numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
# warning: when converting from numpy-> pytorch, pytorch reflects numpy's default
# datatype of float64 unless specified otherwise
tensor = torch.from_numpy(array)
#tensor = torch.from_numpy(array).type(torch.float32)
array, tensor
# default numpy data type is float 64, where as default tensor data type is
# float 32

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [92]:
tensor.dtype

torch.float64

In [93]:
# change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [94]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [95]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# change the tensor,what happens to 'numpy_tensor'
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Reproducibility (trying to take random out of random)**

In short how a neural network learns: start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again...

To reduce the randomness in neural network, the PyTorch comes with the concept of a **random seed**

Essentially what the random seed does is 'flavour' the randomness.

In [96]:
import torch

randomTensor1 = torch.rand(3,4)
randomTensor2 = torch.rand(3,4)

print(randomTensor1)
print(randomTensor2)
print(randomTensor1 == randomTensor2)

tensor([[0.3291, 0.5810, 0.9300, 0.4477],
        [0.4950, 0.7003, 0.2054, 0.6357],
        [0.2804, 0.1325, 0.5424, 0.9706]])
tensor([[0.4905, 0.6165, 0.5208, 0.6495],
        [0.6454, 0.0506, 0.1640, 0.6629],
        [0.8164, 0.4468, 0.4940, 0.4419]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [97]:
# Let's make some random but reproducible tensors.

import torch
# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
randomTensor3 = torch.rand(3,4)

# set it each time for new identical random tensor
torch.manual_seed(RANDOM_SEED) # if this line commented then ans will false.
randomTensor4 = torch.rand(3,4)

print(randomTensor3)
print(randomTensor4)
print(randomTensor3 == randomTensor4)

# study pytorch doc for reproducibility

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [98]:
# importing torch
import torch

# creating a tensors
t1=torch.tensor([1, 2, 3, 4])
t2=torch.tensor([[1, 2, 3, 4],
				[5, 6, 7, 8],
				[9, 10, 11, 12]])

# printing the tensors:
print("Tensor t1: \n", t1)
print("\nTensor t2: \n", t2)

# rank of tensors
print("\nRank of t1: ", len(t1.shape))
print("Rank of t2: ", len(t2.shape))

# shape of tensors
print("\nRank of t1: ", t1.shape)
print("Rank of t2: ", t2.shape)

Tensor t1: 
 tensor([1, 2, 3, 4])

Tensor t2: 
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Rank of t1:  1
Rank of t2:  2

Rank of t1:  torch.Size([4])
Rank of t2:  torch.Size([3, 4])


In [99]:
# importing torch module
import torch
import numpy as np

# list of values to be stored as tensor
data1 = [1, 2, 3, 4, 5, 6]
data2 = np.array([1.5, 3.4, 6.8,
				9.3, 7.0, 2.8])

# creating tensors and printing
t1 = torch.tensor(data1)
t2 = torch.Tensor(data1)
t3 = torch.as_tensor(data2)
t4 = torch.from_numpy(data2)

print("Tensor: ",t1, "Data type: ", t1.dtype,"\n")
print("Tensor: ",t2, "Data type: ", t2.dtype,"\n")
print("Tensor: ",t3, "Data type: ", t3.dtype,"\n")
print("Tensor: ",t4, "Data type: ", t4.dtype,"\n")

Tensor:  tensor([1, 2, 3, 4, 5, 6]) Data type:  torch.int64 

Tensor:  tensor([1., 2., 3., 4., 5., 6.]) Data type:  torch.float32 

Tensor:  tensor([1.5000, 3.4000, 6.8000, 9.3000, 7.0000, 2.8000], dtype=torch.float64) Data type:  torch.float64 

Tensor:  tensor([1.5000, 3.4000, 6.8000, 9.3000, 7.0000, 2.8000], dtype=torch.float64) Data type:  torch.float64 



In [100]:
# import torch module
import torch

# defining two tensors
t1 = torch.tensor([1, 2, 3, 4])
t2 = torch.tensor([5, 6, 7, 8])

# adding two tensors
print("tensor2 + tensor1")
print(torch.add(t2, t1))

# subtracting two tensor
print("\ntensor2 - tensor1")
print(torch.sub(t2, t1))

# multiplying two tensors
print("\ntensor2 * tensor1")
print(torch.mul(t2, t1))

# diving two tensors
print("\ntensor2 / tensor1")
print(torch.div(t2, t1))


tensor2 + tensor1
tensor([ 6,  8, 10, 12])

tensor2 - tensor1
tensor([4, 4, 4, 4])

tensor2 * tensor1
tensor([ 5, 12, 21, 32])

tensor2 / tensor1
tensor([5.0000, 3.0000, 2.3333, 2.0000])


In [101]:
# importing torch module
import torch

# import numpy module
import numpy

# create one dimensional tensor with
# float type elements
b = torch.tensor([10.12, 20.56, 30.00, 40.3, 50.4])

print(b)

# convert this into numpy array using
# numpy() method
b = b.numpy()

# display
b

tensor([10.1200, 20.5600, 30.0000, 40.3000, 50.4000])


array([10.12, 20.56, 30.  , 40.3 , 50.4 ], dtype=float32)

In [103]:
# importing torch module
import torch

# import numpy module
import numpy

# create two dimensional tensor with
# integer type elements
b = torch.tensor([[1, 2, 3, 4, 5], [3, 4, 5, 6, 7],
				[4, 5, 6, 7, 8]])

print(b)

# convert this into numpy array using
# numpy.array() method
b = numpy.array(b)

# display
b

tensor([[1, 2, 3, 4, 5],
        [3, 4, 5, 6, 7],
        [4, 5, 6, 7, 8]])


array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

**Running tensors and pytorch objects on the GPU (& make faster computation)**

**1.Getting a CPU**
* Use Colab free or pro version.
* Use own gpu (costly)
use cloud platform AWS, GCP, Azure etc.

**2. Check for GPU acess with pytorch**


In [122]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [104]:
# see random seed concept on wiki
# change runtime to GPU.
# check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

**2.5 Setting up Device Agnostic code**

For pytorch since it's capable of running compute on gpu or cpu, it's best practice to setup the device agnostic code,
e.g. run on GPU if available, else defalut to CPU

In [105]:
# setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [106]:
# count no of devices
torch.cuda.device_count()

0

**3 Putting tensors (and mobile) on the GPU**

The Reason we want our tensors/models on the GPU is because using a GPU results in faster computations.italicised text

In [107]:
#create a tensor (default on the cpu)
tensor = torch.tensor([1, 2, 3], device="cpu")

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [108]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

**4 Moving tensors back to the CPU**

In [109]:
# numpy on use cpu, so If tensor is on GPU, can't transform it to NumPy

tensor_on_gpu.numpy()

# will throw an error

array([1, 2, 3])

In [110]:
# To fix above issue the GPU tensor with NumPy issue, we can first set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu()
print(tensor_back_on_cpu) # thisis still a tensor not an array

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu) # now this is numpy array

tensor([1, 2, 3])
[1 2 3]


In [111]:
tensor_on_gpu

tensor([1, 2, 3])

**Exercise**

In [112]:
# 1. import torch and create random array with shape (7, 7)
import torch

random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

In [113]:
# now mltipy it wit random tensor of shape (1, 7)

random_tensor2 = torch.rand(1, 7)
random_tensor2

# before performing matmul lets transpose
random_tensor3 = torch.matmul(random_tensor, random_tensor2.T)
random_tensor3

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])

In [114]:
# set random_seed to 0, and again perform above mul
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

random_tensor = torch.rand(7, 7)
random_tensor
random_tensor2 = torch.rand(1, 7)
random_tensor2
random_tensor3 = torch.matmul(random_tensor, random_tensor2.T)
random_tensor3

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [115]:
# create a random seed on the gpu
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)

random_tensor = torch.rand(2, 3).to(device)
random_tensor

random_tensor2 = torch.rand(2, 3).to(device)
random_tensor2

random_tensor3 = torch.matmul(random_tensor, random_tensor2.T)
random_tensor3

print(random_tensor)
print(random_tensor2)
print(random_tensor3)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])
tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])


In [116]:
# finding max and min value of random tensor 3
print(random_tensor3.max())
print(random_tensor3.min())

tensor(0.5617)
tensor(0.3647)


In [117]:
# final exercise

# set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

# create random tensor
random_tensor = torch.rand(1, 1, 1, 10)
random_tensor

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [118]:
# print out tensors and their shapes
print(f"Random tensor: {random_tensor}")
print(f"Random tensor shape: {random_tensor.shape}")

Random tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Random tensor shape: torch.Size([1, 1, 1, 10])


**COMPLETE THE PRACTICAL'S ("SML")**...................................